server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PhamPhucHau/spring-cloud-config-server
#          searchPaths: SpringCloudStationaryAppConfigServer
          default-label: main
          skip-ssl-validation: true

eureka:
  client:
    serviceUrl:
      defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka}