version: '3.7'
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: /eureka-server
      dockerfile: Dockerfile
    hostname: eureka-server
    ports:
      - "8761:8761"
  config-server:
    container_name: config-server
    build:
      context: /configserver
      dockerfile: Dockerfile
    links:
      - eureka-server
    volumes:
      - ./config-data:/var/config-data
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - JAVA_OPTS=
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - "8888:8888"
  getway:
    container_name: gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - "8765:8765"
  currency-exchange-service:
    build:
      context: /currencyexchangeservice
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
    restart: on-failure
    depends_on:
      - eureka-server
      - config-server
    deploy:
      mode: replicated
      replicas: 2
  currency-calculation-service:
    build:
      context: /currencyexchangeservice
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
    restart: on-failure
    depends_on:
      - eureka-server
    deploy:
      mode: replicated
      replicas: 2

  product-service:
    build:
      context: /product
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - "SPRING_PROFILES_ACTIVE=dev"
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
        -Dlogging.level.org.springframework=DEBUG
    restart: on-failure
    links:
      - config-server
    depends_on:
      - eureka-server
      - config-server
    deploy:
      mode: replicated
      replicas: 1
