spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: currency-exchange-service
  profiles:
    active: dev

server:
  port: 8000
# dang ky voi eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: DEBUG